import type { ReactNode } from "react";
import { X } from "lucide-react";

const Section = ({ number, title, children }: { number: string; title: string; children: ReactNode }) => (
  <section className="mt-7 first:mt-0">
    <h3 className="text-sm font-semibold text-foreground">{number}. {title}</h3>
    <div className="mt-2 space-y-3">{children}</div>
  </section>
);

export function DocsPanel({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 px-4 py-6" role="presentation" onMouseDown={onClose}>
      <div role="dialog" aria-modal="true" aria-labelledby="docs-gizmo-title" className="pixel-frame flex max-h-[92dvh] w-full max-w-4xl flex-col bg-terminal" onMouseDown={(event) => event.stopPropagation()}>
        <div className="flex shrink-0 items-center justify-between border-b-2 border-border px-3 py-2"><h2 id="docs-gizmo-title" className="text-pixel text-[10px] text-primary">GIZMO — DOCUMENTATION</h2><button type="button" onClick={onClose} aria-label="Close documentation" className="pixel-frame-inset flex size-7 cursor-pointer items-center justify-center bg-secondary text-primary hover:bg-primary hover:text-primary-foreground"><X className="size-3.5" /></button></div>
        <article className="overflow-y-auto px-5 py-5 text-xs leading-relaxed text-muted-foreground sm:px-8">
          <Section number="1" title="Supported Markets"><p>Gizmo currently focuses on six crypto assets:</p><div className="grid grid-cols-2 gap-1 border-2 border-border p-2 sm:grid-cols-4"><span>Bitcoin — BTC</span><span>Ethereum — ETH</span><span>Solana — SOL</span><span>Hyperliquid — HYPE</span><span>Dogecoin — DOGE</span><span>XRP — XRP</span></div><p>These assets form Gizmo’s current analysis universe. Gizmo can examine relationships between assets within this universe. A particular pair is not assumed to have a lead-lag relationship simply because both assets are included. The relationship must be measured from the available market data.</p></Section>
          <Section number="2" title="What Is Lead-Lag Analysis?"><p>Lead-lag analysis examines whether movements in one asset tend to occur before movements in another asset.</p><p>For example: <span className="text-foreground">BTC → SOL</span> could mean that BTC’s return at one point in time is compared with SOL’s return at a later point. The amount of time between those observations is the lag.</p><p>Lead-lag analysis is useful because related markets do not necessarily react simultaneously. Quantitative lead-lag research therefore attempts to measure the timing and strength of these relationships rather than assuming them.</p></Section>
          <Section number="3" title="Return Analysis"><p>Gizmo analyzes returns rather than simply comparing the absolute prices of BTC, ETH, SOL, HYPE, DOGE and XRP.</p><p>The current research engine uses logarithmic returns:</p><p className="pixel-frame bg-background px-3 py-2 text-center text-foreground">rₜ = ln(Pₜ / Pₜ₋₁)</p><p>This converts price movements into comparable changes and allows the system to analyze relationships between assets with very different price levels.</p></Section>
          <Section number="4" title="Lag Discovery"><p>Gizmo tests potential time lags between a leader and a follower.</p><p>The current research implementation tests an hourly lag range of <span className="text-foreground">1–24 hours</span>. For each candidate lag, Gizmo aligns the leader’s return with the follower’s return at that later point and calculates Pearson correlation. The candidate producing the strongest measured correlation becomes the selected lag.</p><p>Example: <span className="text-foreground">BTC → SOL — Estimated lag: 10H</span>. This means the historical sample showed its strongest measured relationship at that tested lag. It does not mean Gizmo knows that SOL will move exactly ten hours after BTC in the future.</p></Section>
          <Section number="5" title="Regression"><p>After identifying a candidate lag, Gizmo estimates the relationship using linear regression.</p><p className="pixel-frame bg-background px-3 py-2 text-center text-foreground">Follower Return = α + β × Leader Return + Error</p><p>α = intercept; β = estimated sensitivity of the follower to the leader. This gives Gizmo an expected follower return based on the leader’s observed return.</p></Section>
          <Section number="6" title="Residuals"><p>The difference between actual follower return and the model’s expected follower return is the residual.</p><p className="pixel-frame bg-background px-3 py-2 text-center text-foreground">Residual = Actual Follower Return − Expected Follower Return</p><p>The residual is central to Gizmo’s analysis. It represents how far the observed relationship has moved away from what the historical regression model expected.</p></Section>
          <Section number="7" title="Rolling Z-Score"><p>Gizmo standardizes the residual using its recent history.</p><p className="pixel-frame bg-background px-3 py-2 text-center text-foreground">Z = (Residual − Rolling Mean) / Rolling Standard Deviation</p><p>The z-score tells Gizmo how unusual the current residual is relative to recent behavior.</p><ul className="list-disc space-y-1 pl-5"><li><span className="text-foreground">Z ≈ 0</span> — close to its recent average.</li><li><span className="text-foreground">Z &gt; +2</span> — substantially above its recent mean.</li><li><span className="text-foreground">Z &lt; −2</span> — substantially below its recent mean.</li></ul><p>The ±2 level is used as a signal threshold in the current research configuration.</p></Section>
          <Section number="8" title="Mean-Reversion Setups"><p>Gizmo uses these deviations to identify situations that may represent mean-reversion opportunities.</p><p className="text-foreground">Historical relationship → Current deviation → Statistical measurement → Potential reversion</p><ol className="list-decimal space-y-1 pl-5"><li>BTC historically leads SOL by a measured amount.</li><li>BTC moves.</li><li>SOL does not respond as the historical model would expect.</li><li>The residual increases.</li><li>The residual reaches an unusually large z-score.</li><li>Gizmo identifies the deviation.</li><li>Gizmo explains the relationship and provides the relevant data.</li></ol><p>The system does not assume every extreme deviation will revert.</p></Section>
          <Section number="9" title="Signals"><p>When a relationship reaches configured conditions, Gizmo can generate a signal.</p><p>Signals can contain pair, leader, follower, current prices, estimated lag, correlation, alpha, beta, residual, rolling mean, rolling standard deviation, z-score, direction of deviation, timestamp, and historical context.</p><p>The signal gives the user the information needed to investigate the setup.</p></Section>
          <Section number="10" title="Six-Asset Relationship Analysis"><p>Gizmo can investigate relationships such as BTC → ETH, BTC → SOL, BTC → HYPE, BTC → DOGE, BTC → XRP, ETH → SOL, ETH → HYPE, SOL → HYPE, and other combinations within the supported six-asset universe.</p><p>Gizmo does not hard-code the conclusion that one asset leads another. Each relationship is measured from historical data. A pair may show a measurable lag, weak correlation, strong correlation, an unstable relationship, or no useful lead-lag relationship. Gizmo should report the result rather than manufacture a signal.</p></Section>
          <Section number="11" title="Backtesting"><p>Gizmo includes a research layer for testing whether detected relationships and signals would have behaved historically.</p><p><span className="text-foreground">V4</span> introduced training/out-of-sample data, transaction fees, slippage, approximate funding costs, multiple rolling windows, multiple z-score thresholds, multiple forward horizons, and cooldown periods.</p><p>One BTC/SOL V4 run produced 56 training trades with +19.47% training return, while the corresponding out-of-sample test produced 5 trades and +0.16% net return. Those results are research outputs, not evidence of a proven profitable strategy.</p><p><span className="text-foreground">V5</span> introduced a walk-forward research structure. The first V5 implementation produced too few out-of-sample trades to establish meaningful statistical evidence. Gizmo should expose weak evidence rather than hide it.</p></Section>
          <Section number="12" title="Walk-Forward Research"><p>Gizmo’s research architecture is intended to reduce overfitting.</p><p className="text-foreground">Training → Validation → Out-of-Sample Test → Move Forward</p><p>The process is repeated across historical periods to evaluate whether a relationship or configuration continues to behave on data that was not used to select it.</p></Section>
          <Section number="13" title="Monitoring"><p>Gizmo can continuously monitor supported market relationships. The current system includes scheduled monitoring and a signal store, allowing Gizmo to move from “Run an analysis” to “Continue watching these relationships and tell me when something statistically interesting occurs.”</p></Section>
          <Section number="14" title="Conversational Analysis"><p>The quantitative engine produces the measurements. The Gizmo agent interprets them.</p><p>Users can ask what is happening between BTC and SOL, which asset is leading, the current lag, the z-score, how unusual a deviation is, the latest signals, whether a relationship has behaved like this before, or how BTC/SOL compares with ETH/SOL.</p><p>Gizmo’s responses should be based on actual outputs of its analysis tools and available market data.</p></Section>
          <Section number="15" title="What Gizmo Does Not Do"><p>Gizmo is not a trading execution system.</p><ul className="list-disc space-y-1 pl-5"><li>Place trades</li><li>Execute trades</li><li>Manage positions</li><li>Move user funds</li><li>Decide how much a user should risk</li><li>Guarantee that a signal will work</li><li>Guarantee mean reversion</li><li>Present historical backtests as future performance</li><li>Make the final trading decision for the user</li></ul><p className="text-foreground">Data → Analysis → Signal → Explanation</p><p>The user decides what happens next.</p></Section>
          <Section number="16" title="Product Architecture"><p className="text-foreground">Market Data → Quantitative Engine → Signal Layer → Monitoring → Agent Layer → Conversational UI</p><p>Market Data collects required inputs. The Quantitative Engine calculates returns, correlations, lags, regression, residuals and z-scores. The Signal Layer identifies configured statistical deviations. Monitoring continuously checks relationships. The Agent Layer interprets quantitative results. The Conversational UI lets users investigate the market through Gizmo.</p><p>The interface is the front end for Gizmo’s quantitative analysis system, not a generic AI chatbot.</p></Section>
          <Section number="17" title="The Gizmo Workflow"><p className="text-foreground">Six crypto assets → Measure relationships → Discover potential lead-lag relationships → Model expected behavior → Calculate residuals → Measure deviations with z-scores → Detect potential mean-reversion setups → Monitor relationships over time → Explain the data conversationally → User makes the decision</p></Section>
          <Section number="18" title="Research Philosophy"><p>Gizmo is built around a simple principle:</p><p className="text-base text-primary">Don’t tell the user what to trade. Show them what the data is saying.</p><p>A strong signal should be accompanied by its context. A weak relationship should be identified as weak. A failed backtest should remain visible. An insufficient sample should be acknowledged. An unusual z-score should be treated as an observation, not a guarantee.</p><p>That is what makes Gizmo a quantitative research and intelligence product rather than another black-box crypto signal bot.</p></Section>
        </article>
      </div>
    </div>
  );
}
